FROM centos:centos7

WORKDIR /app

RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum -y install yum-utils
RUN yum-builddep -y octave
RUN yum -y install g++ make pcre2 blas-devel lapack-devel gfortran libtool readline-devel lzip mercurial automake wget

## Download Octave 4.4.1 release, unpack, build
COPY octave-4.4.1.tar.lz.sha1 /app
RUN wget https://ftp.gnu.org/gnu/octave/octave-4.4.1.tar.lz

RUN sha1sum -c octave-4.4.1.tar.lz.sha1 &&\
    tar --lzip -xvf octave-4.4.1.tar.lz

RUN yum -y install gcc-c++

RUN mkdir octave-4.4.1-build &&\
    cd octave-4.4.1-build &&\
    ../octave-4.4.1/configure --disable-java --disable-docs &&\
    make -j8

RUN cd octave-4.4.1-build && make install

RUN yum -y install http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
RUN yum -y install ffmpeg-devel 

COPY ./video-*.tar.gz /app/

RUN octave --eval "pkg install -verbose video-*.tar.gz"

CMD ["/bin/bash"]
