FROM fedora:31

WORKDIR /app

RUN dnf -y install octave
RUN dnf -y install octave-devel

RUN dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
RUN dnf -y install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
RUN dnf -y install ffmpeg ffmpeg-devel

RUN dnf -y install make patch redhat-rpm-config

COPY ./video-*.tar.gz /app

RUN octave --eval "pkg install -verbose video-*.tar.gz"

CMD ["/bin/bash"]


